
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentManagement.Models
{

using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
public partial class AbsentCalendar : BaseViewModel
{

    private System.Guid _id { get; set; }
    public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }

    private Nullable<System.Guid> _idSubjectClass { get; set; }
    public Nullable<System.Guid> IdSubjectClass { get => _idSubjectClass; set { _idSubjectClass = value; OnPropertyChanged(); } }

    private Nullable<System.DateTime> _date { get; set; }
    public Nullable<System.DateTime> Date { get => _date; set { _date = value; OnPropertyChanged(); } }

    private Nullable<int> _type { get; set; }
    public Nullable<int> Type { get => _type; set { _type = value; OnPropertyChanged(); } }

    private string _period { get; set; }
    public string Period { get => _period; set { _period = value; OnPropertyChanged(); } }



    public virtual SubjectClass SubjectClass { get; set; }

}

}
