//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdUsers { get; set; }
    
        public virtual User User { get; set; }
    }
}
