//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRegister
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid IdStudent { get; set; }
        public System.Guid IdSubjectClass { get; set; }
        public System.Guid IdSemester { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
        public virtual SubjectClass SubjectClass { get; set; }
    }
}
