
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentManagement.Models
{

using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
public partial class CourseRegister : BaseViewModel
{

    private System.Guid _id { get; set; }
    public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }

    private Nullable<int> _status { get; set; }
    public Nullable<int> Status { get => _status; set { _status = value; OnPropertyChanged(); } }

    private System.Guid _idStudent { get; set; }
    public System.Guid IdStudent { get => _idStudent; set { _idStudent = value; OnPropertyChanged(); } }

    private System.Guid _idSubjectClass { get; set; }
    public System.Guid IdSubjectClass { get => _idSubjectClass; set { _idSubjectClass = value; OnPropertyChanged(); } }

    private System.Guid _idSemester { get; set; }
    public System.Guid IdSemester { get => _idSemester; set { _idSemester = value; OnPropertyChanged(); } }



    public virtual Semester Semester { get; set; }

    public virtual Student Student { get; set; }

    public virtual SubjectClass SubjectClass { get; set; }

}

}
