//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseImageTable
    {
        public DatabaseImageTable()
        {
            this.Classes = new HashSet<Class>();
            this.SubjectClasses = new HashSet<SubjectClass>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<SubjectClass> SubjectClasses { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
