//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseImageTable : BaseViewModel
    {
        public DatabaseImageTable()
        {
            this.Classes = new HashSet<Class>();
            this.NotificationImages = new HashSet<NotificationImage>();
            this.SubjectClasses = new HashSet<SubjectClass>();
            this.Users = new HashSet<User>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _image { get; set; }
        public string Image { get => _image; set { _image = value; OnPropertyChanged(); } }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<NotificationImage> NotificationImages { get; set; }
        public virtual ICollection<SubjectClass> SubjectClasses { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
