//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailScore
    {
        public System.Guid Id { get; set; }
        public System.Guid IdStudent { get; set; }
        public System.Guid IdComponentScore { get; set; }
        public Nullable<double> Score { get; set; }
    
        public virtual ComponentScore ComponentScore { get; set; }
        public virtual Student Student { get; set; }
    }
}
