//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public System.Guid IdPoster { get; set; }
        public Nullable<System.Guid> IdFolder { get; set; }
        public System.Guid IdSubjectClass { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual User User { get; set; }
        public virtual SubjectClass SubjectClass { get; set; }
    }
}
