//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get; set; }
        public string ExamName { get; set; }
        public string WeekDay { get; set; }
        public string Period { get; set; }
    
        public virtual SubjectClass SubjectClass { get; set; }
    }
}
