//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Examination : BaseViewModel
    {
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idSubjectClass { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get => _idSubjectClass; set { _idSubjectClass = value; OnPropertyChanged(); } }
        private string _examName { get; set; }
        public string ExamName { get => _examName; set { _examName = value; OnPropertyChanged(); } }
        private string _weekDay { get; set; }
        public string WeekDay { get => _weekDay; set { _weekDay = value; OnPropertyChanged(); } }
        private string _period { get; set; }
        public string Period { get => _period; set { _period = value; OnPropertyChanged(); } }
    
        public virtual SubjectClass SubjectClass { get; set; }
    }
}
