//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentManagementEntities : DbContext
    {
        public StudentManagementEntities()
            : base("name=StudentManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AbsentCalendar> AbsentCalendars { get; set; }
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<ComponentScore> ComponentScores { get; set; }
        public DbSet<CourseRegister> CourseRegisters { get; set; }
        public DbSet<DatabaseImageTable> DatabaseImageTables { get; set; }
        public DbSet<DetailScore> DetailScores { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Examination> Examinations { get; set; }
        public DbSet<Faculty> Falcuties { get; set; }
        public DbSet<Faculty_TrainingForm> Faculty_TrainingForm { get; set; }
        public DbSet<Folder> Folders { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Semester> Semesters { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudyResult> StudyResults { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<SubjectClass> SubjectClasses { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TrainingForm> TrainingForms { get; set; }
        public DbSet<TrainingScore> TrainingScores { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
