//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Notification : BaseViewModel
    {
        public Notification()
        {
            this.NotificationInfoes = new HashSet<NotificationInfo>();
            this.NotificationComments = new HashSet<NotificationComment>();
            this.NotificationImages = new HashSet<NotificationImage>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _topic { get; set; }
        public string Topic { get => _topic; set { _topic = value; OnPropertyChanged(); } }
        private string _content { get; set; }
        public string Content { get => _content; set { _content = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _time { get; set; }
        public Nullable<System.DateTime> Time { get => _time; set { _time = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idNotificationType { get; set; }
        public Nullable<System.Guid> IdNotificationType { get => _idNotificationType; set { _idNotificationType = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idPoster { get; set; }
        public Nullable<System.Guid> IdPoster { get => _idPoster; set { _idPoster = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idSubjectClass { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get => _idSubjectClass; set { _idSubjectClass = value; OnPropertyChanged(); } }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<NotificationInfo> NotificationInfoes { get; set; }
        public virtual ICollection<NotificationComment> NotificationComments { get; set; }
        public virtual ICollection<NotificationImage> NotificationImages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual SubjectClass SubjectClass { get; set; }
        public virtual SubjectClass SubjectClass1 { get; set; }
    }
}
