//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class OTP : BaseViewModel
    {
        public OTP()
        {
            this.Users = new HashSet<User>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _code { get; set; }
        public string Code { get => _code; set { _code = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _time { get; set; }
        public Nullable<System.DateTime> Time { get => _time; set { _time = value; OnPropertyChanged(); } }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
