//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.CourseRegisters = new HashSet<CourseRegister>();
            this.SubjectClasses = new HashSet<SubjectClass>();
            this.TrainingScores = new HashSet<TrainingScore>();
        }
    
        public System.Guid Id { get; set; }
        public string Batch { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CourseRegisterStatus { get; set; }
    
        public virtual ICollection<CourseRegister> CourseRegisters { get; set; }
        public virtual ICollection<SubjectClass> SubjectClasses { get; set; }
        public virtual ICollection<TrainingScore> TrainingScores { get; set; }
    }
}
