//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Student : BaseViewModel
    {
        public Student()
        {
            this.CourseRegisters = new HashSet<CourseRegister>();
            this.DetailScores = new HashSet<DetailScore>();
            this.StudyResults = new HashSet<StudyResult>();
            this.TrainingScores = new HashSet<TrainingScore>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idTrainingForm { get; set; }
        public Nullable<System.Guid> IdTrainingForm { get => _idTrainingForm; set { _idTrainingForm = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idFaculty { get; set; }
        public Nullable<System.Guid> IdFaculty { get => _idFaculty; set { _idFaculty = value; OnPropertyChanged(); } }
        private Nullable<int> _status { get; set; }
        public Nullable<int> Status { get => _status; set { _status = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idUsers { get; set; }
        public Nullable<System.Guid> IdUsers { get => _idUsers; set { _idUsers = value; OnPropertyChanged(); } }
    
        public virtual ICollection<CourseRegister> CourseRegisters { get; set; }
        public virtual ICollection<DetailScore> DetailScores { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual TrainingForm TrainingForm { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StudyResult> StudyResults { get; set; }
        public virtual ICollection<TrainingScore> TrainingScores { get; set; }
    }
}
