//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.CourseRegisters = new HashSet<CourseRegister>();
            this.DetailScores = new HashSet<DetailScore>();
            this.StudyResults = new HashSet<StudyResult>();
            this.TrainingScores = new HashSet<TrainingScore>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdTrainingForm { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> IdUsers { get; set; }
        public Nullable<System.Guid> IdParent { get; set; }
    
        public virtual ICollection<CourseRegister> CourseRegisters { get; set; }
        public virtual ICollection<DetailScore> DetailScores { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual TrainingForm TrainingForm { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StudyResult> StudyResults { get; set; }
        public virtual ICollection<TrainingScore> TrainingScores { get; set; }
    }
}
