//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.SubjectClasses = new HashSet<SubjectClass>();
        }
    
        public System.Guid Id { get; set; }
        public string Credit { get; set; }
        public string DisplayName { get; set; }
        public string Code { get; set; }
        public string Describe { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<SubjectClass> SubjectClasses { get; set; }
    }
}
