//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectClass
    {
        public SubjectClass()
        {
            this.AbsentCalendars = new HashSet<AbsentCalendar>();
            this.ComponentScores = new HashSet<ComponentScore>();
            this.CourseRegisters = new HashSet<CourseRegister>();
            this.Documents = new HashSet<Document>();
            this.Examinations = new HashSet<Examination>();
            this.Folders = new HashSet<Folder>();
            this.StudyResults = new HashSet<StudyResult>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdSubject { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> IdSemester { get; set; }
        public string Period { get; set; }
        public string WeekDay { get; set; }
        public System.Guid IdThumbnail { get; set; }
    
        public virtual ICollection<AbsentCalendar> AbsentCalendars { get; set; }
        public virtual ICollection<ComponentScore> ComponentScores { get; set; }
        public virtual ICollection<CourseRegister> CourseRegisters { get; set; }
        public virtual DatabaseImageTable DatabaseImageTable { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Examination> Examinations { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual ICollection<StudyResult> StudyResults { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
