//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_SubjectClass : BaseViewModel
    {
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idSubjectClass { get; set; }
        public Nullable<System.Guid> IdSubjectClass { get => _idSubjectClass; set { _idSubjectClass = value; OnPropertyChanged(); } }
        private Nullable<System.Guid> _idTeacher { get; set; }
        public Nullable<System.Guid> IdTeacher { get => _idTeacher; set { _idTeacher = value; OnPropertyChanged(); } }
    
        public virtual SubjectClass SubjectClass { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
