//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingForm
    {
        public TrainingForm()
        {
            this.Classes = new HashSet<Class>();
            this.Falcuty_TrainingForm = new HashSet<Falcuty_TrainingForm>();
            this.Students = new HashSet<Student>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Falcuty_TrainingForm> Falcuty_TrainingForm { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
