//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoItem : BaseViewModel
    {
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private System.Guid _idUserInfo { get; set; }
        public System.Guid IdUserInfo { get => _idUserInfo; set { _idUserInfo = value; OnPropertyChanged(); } }
        private string _content { get; set; }
        public string Content { get => _content; set { _content = value; OnPropertyChanged(); } }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
