//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole : BaseViewModel
    {
        public UserRole()
        {
            this.UserRole_UserInfo = new HashSet<UserRole_UserInfo>();
            this.Users = new HashSet<User>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _role { get; set; }
        public string Role { get => _role; set { _role = value; OnPropertyChanged(); } }
    
        public virtual ICollection<UserRole_UserInfo> UserRole_UserInfo { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
