//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo : BaseViewModel
    {
        public UserInfo()
        {
            this.UserInfoItems = new HashSet<UserInfoItem>();
            this.UserRole_UserInfo = new HashSet<UserRole_UserInfo>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _infoName { get; set; }
        public string InfoName { get => _infoName; set { _infoName = value; OnPropertyChanged(); } }
        private Nullable<int> _type { get; set; }
        public Nullable<int> Type { get => _type; set { _type = value; OnPropertyChanged(); } }
    
        public virtual ICollection<UserInfoItem> UserInfoItems { get; set; }
        public virtual ICollection<UserRole_UserInfo> UserRole_UserInfo { get; set; }
    }
}
