//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using StudentManagement.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_UserInfo : BaseViewModel
    {
        public UserRole_UserInfo()
        {
            this.User_UserRole_UserInfo = new HashSet<User_UserRole_UserInfo>();
        }
    
        private System.Guid _id { get; set; }
        public System.Guid Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private System.Guid _idRole { get; set; }
        public System.Guid IdRole { get => _idRole; set { _idRole = value; OnPropertyChanged(); } }
        private System.Guid _idUserInfo { get; set; }
        public System.Guid IdUserInfo { get => _idUserInfo; set { _idUserInfo = value; OnPropertyChanged(); } }
        private Nullable<bool> _isEnable { get; set; }
        public Nullable<bool> IsEnable { get => _isEnable; set { _isEnable = value; OnPropertyChanged(); } }
        private Nullable<bool> _isDeleted { get; set; }
        public Nullable<bool> IsDeleted { get => _isDeleted; set { _isDeleted = value; OnPropertyChanged(); } }
    
        public virtual ICollection<User_UserRole_UserInfo> User_UserRole_UserInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
